//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class average_performance_broadband
    {
        public Nullable<int> county_id_fk { get; set; }
        public Nullable<decimal> Average_Speed_mbps { get; set; }
        public Nullable<decimal> Average_Pass_of_5_GCSES { get; set; }
        public int id { get; set; }
    }
}
