//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class county_performance_broadband_rankings
    {
        public int county_id { get; set; }
        public string county_name { get; set; }
        public Nullable<decimal> average_speed { get; set; }
        public Nullable<decimal> average_pass { get; set; }
        public Nullable<int> speed_ranking { get; set; }
        public Nullable<int> pass_ranking { get; set; }
    }
}
