//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class local_authority_population_sync_speed
    {
        public int id { get; set; }
        public string authority { get; set; }
        public Nullable<long> population_size { get; set; }
        public decimal average_sync_speed_mBits { get; set; }
    }
}
