//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class passrates_broadband_ranked
    {
        public int id { get; set; }
        public string school { get; set; }
        public decimal average_speed { get; set; }
        public decimal percent_passed { get; set; }
        public int speed_rank { get; set; }
        public int pass_rank { get; set; }
    }
}
