//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spearmans_ranks
    {
        public int correlation_id { get; set; }
        public string correlation_name { get; set; }
        public decimal spearmans_rho { get; set; }
    }
}
