//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_passrates_by_broadband
    {
        public string postcode { get; set; }
        public Nullable<decimal> average_speed_mbps { get; set; }
        public decimal percent_5_pass_grades_gcse { get; set; }
        public string school_name { get; set; }
    }
}
